#!/usr/bin/env bash
# 发件服务地址
export MAIL_SERVER=smtp.qq.com
# 发件服务端口
export MAIL_PORT=587
# 发件人账户
export MAIL_USERNAME=809390770@qq.com
# 发件人token，非账户密码，需要再邮箱中申请token
export MAIL_PASSWORD=tzfpcxolpvopbfej
